// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeatherSearchClient is the client API for WeatherSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherSearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type weatherSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherSearchClient(cc grpc.ClientConnInterface) WeatherSearchClient {
	return &weatherSearchClient{cc}
}

func (c *weatherSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/goweather.WeatherSearch/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherSearchServer is the server API for WeatherSearch service.
// All implementations must embed UnimplementedWeatherSearchServer
// for forward compatibility
type WeatherSearchServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedWeatherSearchServer()
}

// UnimplementedWeatherSearchServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherSearchServer struct {
}

func (UnimplementedWeatherSearchServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedWeatherSearchServer) mustEmbedUnimplementedWeatherSearchServer() {}

// UnsafeWeatherSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherSearchServer will
// result in compilation errors.
type UnsafeWeatherSearchServer interface {
	mustEmbedUnimplementedWeatherSearchServer()
}

func RegisterWeatherSearchServer(s grpc.ServiceRegistrar, srv WeatherSearchServer) {
	s.RegisterService(&WeatherSearch_ServiceDesc, srv)
}

func _WeatherSearch_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherSearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goweather.WeatherSearch/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherSearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherSearch_ServiceDesc is the grpc.ServiceDesc for WeatherSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goweather.WeatherSearch",
	HandlerType: (*WeatherSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _WeatherSearch_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weathersearch.proto",
}
